#cloud-config
hostname: pjg
users:
- name: pg
  passwd: $1$6mDJ9GfH$PKGcSFC3KQRXum65l8Vpp1
  groups:
  - sudo
  - docker
  ssh-authorized-keys:
  - ssh-rsa - AAAAB3NzaC1yc2EAAAADAQABAAABAQDF+J8gy6NVe4l0GgV6FBHOSiJ/WEriAfVsfwNii47VMK+2e+0BA8M/18DzwmEu7OyqiDASHCGsZxQNNUjhwPiQGAaNJkIloozWJZomDS34OCLfga/zhyEwGXKXGZsARpe85CZJMsvPXUuOfCBNmi8RtEp9jwf2y7Hh/BGfJY7E9T9cvuRRdIUZsK1uwnpSM0m0XJq6Ocj/AUJnDKNNBKZqQupwm++aay6adjV8DhqTGc2r4NStOLlnMMC2s1qiAsv2s2BoNRDMCzVhJBC2TFaWny2pfzxsA+ZWhd1JGNHKe3WjzRayu1RuyyuxUCGs+jj/FJwnOBhnY/GoBQb5Z9wZ
  - ssh-rsa - AAAAB3NzaC1yc2EAAAADAQABAAABAQDIwgH5nbAPjiMjQQaE+BDNztpAYFNQ/qZSKst1wzqLcgh6njaEAzzZik7a5Z9Kxk86l4Q/EQx1GrozfVmQos6/sAHCClOQdo604J3Q51yey81nvv4ykpUs51lUm+ZQcoJ/2ZfB4l1so3DY1SU1TrpIR/5FgpLHxCScGnkjiZwIccVxvUlI7t0Dw8o1hpF6hz3BvfCNiQQmXse3M2LvhCUsdPYCfig8cmoUpqqqtO9QVrCFIwTk3LKjKnzcDK8sSrbuENjkLlghlrgLQcBLrZZx3ZMAeopwgL76NgvwMuU29BDyuJPEUazeEg2IzFRlgqiYwyMX8VoaKaLAW7M7MYjl
  - ssh-rsa - AAAAB3NzaC1yc2EAAAADAQABAAABAQDvyZrtMR/WH57L3RbKC6c72ecwL7EVbTWaAPtLynp8510KtwEqmxvJVFoLz1BRKYEc5evgQ0nEWkxl2rLt4rwiD0vBoKnc/KSswRImXZDcxfWpOOCmVGzqo7zVhmmio5N6S8FBVCxTuq0/UUHZz5RgrE4EwzTWBWubee6Pr+J3w4CokkfhOlwMfFXvqEnPl0SLOZ/L0uT1v8DUj8pGyLniZfCHlQO0SyR/wjlrKsIKMAl6d8Gmg+XkjwrXuaOPV4mF8bghkD3rizT7pi4vL34JBglbyjmZi223Cdgd1pp6JTs5fm9lHUMudjSr3n+qVX6rV+n/KQxKagQXj62PwnVT
coreos:
  units:
  - name: docker.service
    command: start
